### PR TITLE
Updating kysely to latest

### PR DESCRIPTION
**Pull request by vojto**
Also, shouldn't kysely be a peer dependency?

### CODE REVIEW

**Comment by DawidWetzler** [comment]
Hey there, thanks for your pull request!

I'm not sure what `build` has to do with bumping *kysely* to latest, can you please explain?

**Comment by a-type** [comment]
Kysely should be a peer dep, I was just coming over to make my own PR! It will have to be added to `devDependencies` for this package too so it's still installed for local development.

FYI for maintainers, the reason this matters is because end users will be installing a different version of Kysely than the one installed by this package, leading to conflicts. `peerDependencies` is appropriate for package dependencies which you expect users to install separately, as the docs rightly instruct users to do already.

**Comment by DawidWetzler** [comment]
Yes, definitely getting the point of peerDependency and should’ve done it upfront but somehow I missed that.

Glad there are people that do want to improve this package, thanks!

Although even with this pull request this won’t be fixed. I’m not able to access my personal computer for the next 10 days when I’m back I could also fix it myself in case.

**Comment by DawidWetzler** [comment]
Closing in favor of #2.

**Pull request closed without merging**
